// <auto-generated />
using System;
using CourseFlow.Api;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourseFlow.Api.Migrations.Application
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("course_flow")
                .HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("CourseFlow.Api.Course", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("WorkloadHours")
                        .HasColumnType("INTEGER")
                        .HasColumnName("workload_hours");

                    b.HasKey("Id")
                        .HasName("pk_courses");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_courses_category");

                    b.HasIndex("Title")
                        .IsUnique()
                        .HasDatabaseName("ix_courses_title");

                    b.ToTable("courses", "course_flow");
                });

            modelBuilder.Entity("CourseFlow.Api.Enrollment", b =>
                {
                    b.Property<string>("CourseId")
                        .HasColumnType("TEXT")
                        .HasColumnName("course_id");

                    b.Property<string>("StudentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("student_id");

                    b.Property<DateTime>("EnrollmentDateUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2026, 2, 6, 14, 46, 1, 792, DateTimeKind.Utc).AddTicks(6763))
                        .HasColumnName("enrollment_date_utc");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.HasKey("CourseId", "StudentId")
                        .HasName("pk_enrollments");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_enrollments_status");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_enrollments_student_id");

                    b.ToTable("enrollments", "course_flow");
                });

            modelBuilder.Entity("CourseFlow.Api.Student", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasColumnName("full_name");

                    b.Property<DateTime>("RegisteredAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("registered_at_utc");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_students");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_students_email");

                    b.ToTable("students", "course_flow");
                });

            modelBuilder.Entity("CourseFlow.Api.Enrollment", b =>
                {
                    b.HasOne("CourseFlow.Api.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_enrollments_courses_course_id");

                    b.HasOne("CourseFlow.Api.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_enrollments_students_student_id");

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CourseFlow.Api.Course", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("CourseFlow.Api.Student", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
